/**
 * Common Crypto Utilities for ABDFN Suite.
 * Implementation of industrial-strength algorithms in pure JS for zero-knowledge environments.
 */

/**
 * Calculates a standard MD5 hash (32 hex characters).
 * Optimized for performance and parity with legacy industrial witnesses.
 */
export function md5(text: string): string {
  const s = [
    7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22,
    5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20,
    4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23,
    6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21
  ];
  
  const k = Array.from({ length: 64 }, (_, i) => Math.floor(Math.abs(Math.sin(i + 1)) * 4294967296));
  
  const rotateLeft = (l: number, r: number) => (l << r) | (l >>> (32 - r));

  const msg = new TextEncoder().encode(text);
  const words = new Int32Array(((msg.length + 8) >> 6 << 4) + 16);
  for (let i = 0; i < msg.length; i++) words[i >> 2] |= msg[i] << (i % 4 << 3);
  words[msg.length >> 2] |= 0x80 << (msg.length % 4 << 3);
  words[words.length - 2] = msg.length << 3;
  
  let h0 = 1732584193;
  let h1 = -271733879;
  let h2 = -1732584194;
  let h3 = 271733878;
  
  for (let i = 0; i < words.length; i += 16) {
    let a = h0, b = h1, c = h2, d = h3;
    for (let j = 0; j < 64; j++) {
      let f, g;
      if (j < 16) {
        f = (b & c) | (~b & d);
        g = j;
      } else if (j < 32) {
        f = (d & b) | (~d & c);
        g = (5 * j + 1) % 16;
      } else if (j < 48) {
        f = b ^ c ^ d;
        g = (3 * j + 5) % 16;
      } else {
        f = c ^ (b | ~d);
        g = (7 * j) % 16;
      }
      const tmp = d;
      d = c;
      c = b;
      b = (b + rotateLeft((a + f + k[j] + words[i + g]), s[j])) | 0;
      a = tmp;
    }
    h0 = (h0 + a) | 0;
    h1 = (h1 + b) | 0;
    h2 = (h2 + c) | 0;
    h3 = (h3 + d) | 0;
  }
  
  const toHex = (n: number) => ('00000000' + (n >>> 0).toString(16)).slice(-8).match(/../g)!.reverse().join('');
  return toHex(h0) + toHex(h1) + toHex(h2) + toHex(h3);
}

// ERA 5: Industrial Crypto Standards (AES-GCM + PBKDF2)

/**
 * Derives a secure 256-bit key from a password and salt using PBKDF2.
 * Compliance: 04-compliance-security
 */
export async function deriveKey(password: string, salt: Uint8Array): Promise<CryptoKey> {
  const encoder = new TextEncoder();
  const baseKey = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveKey']
  );

  return crypto.subtle.deriveKey(
    {
      name: 'PBKDF2',
      salt,
      iterations: 100000,
      hash: 'SHA-256'
    } as Pbkdf2Params,
    baseKey,
    { name: 'AES-GCM', length: 256 },
    true,
    ['encrypt', 'decrypt']
  );
}

/**
 * Encrypts a string using AES-GCM.
 * Returns a combined Uint8Array: [salt(16) | iv(12) | ciphertext]
 */
export async function encryptData(text: string, password: string): Promise<Uint8Array> {
  const encoder = new TextEncoder();
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  
  const key = await deriveKey(password, salt);
  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    encoder.encode(text)
  );

  const result = new Uint8Array(salt.length + iv.length + encrypted.byteLength);
  result.set(salt, 0);
  result.set(iv, salt.length);
  result.set(new Uint8Array(encrypted), salt.length + iv.length);
  
  return result;
}

/**
 * Decrypts a Uint8Array generated by encryptData.
 */
export async function decryptData(combined: Uint8Array, password: string): Promise<string> {
  const salt = combined.slice(0, 16);
  const iv = combined.slice(16, 28);
  const ciphertext = combined.slice(28);
  
  const key = await deriveKey(password, salt);
  const decrypted = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv },
    key,
    ciphertext
  );

  return new TextDecoder().decode(decrypted);
}
