
export { NO_TIN_JURISDICTIONS } from './no-tin-map';
import { buildRegistry, buildMetadataRegistryWithDescription } from './registry-utils';
import { TinInfo, CountryRegulatoryInfo, TinValidationResult } from './types';

// --- JURISDICTIONAL PLUGIN IMPORTS (Era 6.3 Standard) ---
import { validateADTIN, TIN_INFO as AD_INFO, TIN_REQUIREMENTS as AD_REQUIREMENTS, COUNTRY_INFO as AD_COUNTRY } from './ad-tin';
import { validateAETIN, TIN_INFO as AE_INFO, TIN_REQUIREMENTS as AE_REQUIREMENTS, COUNTRY_INFO as AE_COUNTRY } from './ae-tin';
import { validateAFTIN, TIN_INFO as AF_INFO, TIN_REQUIREMENTS as AF_REQUIREMENTS, COUNTRY_INFO as AF_COUNTRY } from './af-tin';
import { validateAGTIN, TIN_INFO as AG_INFO, TIN_REQUIREMENTS as AG_REQUIREMENTS, COUNTRY_INFO as AG_COUNTRY } from './ag-tin';
import { validateAITIN, TIN_INFO as AI_INFO, TIN_REQUIREMENTS as AI_REQUIREMENTS, COUNTRY_INFO as AI_COUNTRY } from './ai-tin';
import { validateALTIN, TIN_INFO as AL_INFO, TIN_REQUIREMENTS as AL_REQUIREMENTS, COUNTRY_INFO as AL_COUNTRY } from './al-tin';
import { validateAMTIN, TIN_INFO as AM_INFO, TIN_REQUIREMENTS as AM_REQUIREMENTS, COUNTRY_INFO as AM_COUNTRY } from './am-tin';
import { validateAOTIN, TIN_INFO as AO_INFO, TIN_REQUIREMENTS as AO_REQUIREMENTS, COUNTRY_INFO as AO_COUNTRY } from './ao-tin';
import { validateARTIN, TIN_INFO as AR_INFO, TIN_REQUIREMENTS as AR_REQUIREMENTS, COUNTRY_INFO as AR_COUNTRY } from './ar-tin';
import { validateATTIN, TIN_INFO as AT_INFO, TIN_REQUIREMENTS as AT_REQUIREMENTS, COUNTRY_INFO as AT_COUNTRY } from './at-tin';
import { validateAUTIN, TIN_INFO as AU_INFO, TIN_REQUIREMENTS as AU_REQUIREMENTS, COUNTRY_INFO as AU_COUNTRY } from './au-tin';
import { validateAWTIN, TIN_INFO as AW_INFO, TIN_REQUIREMENTS as AW_REQUIREMENTS, COUNTRY_INFO as AW_COUNTRY } from './aw-tin';
import { validateAZTIN, TIN_INFO as AZ_INFO, TIN_REQUIREMENTS as AZ_REQUIREMENTS, COUNTRY_INFO as AZ_COUNTRY } from './az-tin';
import { validateBATIN, TIN_INFO as BA_INFO, TIN_REQUIREMENTS as BA_REQUIREMENTS, COUNTRY_INFO as BA_COUNTRY } from './ba-tin';
import { validateBBTIN, TIN_INFO as BB_INFO, TIN_REQUIREMENTS as BB_REQUIREMENTS, COUNTRY_INFO as BB_COUNTRY } from './bb-tin';
import { validateBDTIN, TIN_INFO as BD_INFO, TIN_REQUIREMENTS as BD_REQUIREMENTS, COUNTRY_INFO as BD_COUNTRY } from './bd-tin';
import { validateBETIN, TIN_INFO as BE_INFO, TIN_REQUIREMENTS as BE_REQUIREMENTS, COUNTRY_INFO as BE_COUNTRY } from './be-tin';
import { validateBFTIN, TIN_INFO as BF_INFO, TIN_REQUIREMENTS as BF_REQUIREMENTS, COUNTRY_INFO as BF_COUNTRY } from './bf-tin';
import { validateBGTIN, TIN_INFO as BG_INFO, TIN_REQUIREMENTS as BG_REQUIREMENTS, COUNTRY_INFO as BG_COUNTRY } from './bg-tin';
import { validateBHTIN, TIN_INFO as BH_INFO, TIN_REQUIREMENTS as BH_REQUIREMENTS, COUNTRY_INFO as BH_COUNTRY } from './bh-tin';
import { validateBITIN, TIN_INFO as BI_INFO, TIN_REQUIREMENTS as BI_REQUIREMENTS, COUNTRY_INFO as BI_COUNTRY } from './bi-tin';
import { validateBJTIN, TIN_INFO as BJ_INFO, TIN_REQUIREMENTS as BJ_REQUIREMENTS, COUNTRY_INFO as BJ_COUNTRY } from './bj-tin';
import { validateBNTIN, TIN_INFO as BN_INFO, TIN_REQUIREMENTS as BN_REQUIREMENTS, COUNTRY_INFO as BN_COUNTRY } from './bn-tin';
import { validateBOTIN, TIN_INFO as BO_INFO, TIN_REQUIREMENTS as BO_REQUIREMENTS, COUNTRY_INFO as BO_COUNTRY } from './bo-tin';
import { validateBQTIN, TIN_INFO as BQ_INFO, TIN_REQUIREMENTS as BQ_REQUIREMENTS, COUNTRY_INFO as BQ_COUNTRY } from './bq-tin';
import { validateBRTIN, TIN_INFO as BR_INFO, TIN_REQUIREMENTS as BR_REQUIREMENTS, COUNTRY_INFO as BR_COUNTRY } from './br-tin';
import { validateBSTIN, TIN_INFO as BS_INFO, TIN_REQUIREMENTS as BS_REQUIREMENTS, COUNTRY_INFO as BS_COUNTRY } from './bs-tin';
import { validateBTTIN, TIN_INFO as BT_INFO, TIN_REQUIREMENTS as BT_REQUIREMENTS, COUNTRY_INFO as BT_COUNTRY } from './bt-tin';
import { validateBWTIN, TIN_INFO as BW_INFO, TIN_REQUIREMENTS as BW_REQUIREMENTS, COUNTRY_INFO as BW_COUNTRY } from './bw-tin';
import { validateBYTIN, TIN_INFO as BY_INFO, TIN_REQUIREMENTS as BY_REQUIREMENTS, COUNTRY_INFO as BY_COUNTRY } from './by-tin';
import { validateBZTIN, TIN_INFO as BZ_INFO, TIN_REQUIREMENTS as BZ_REQUIREMENTS, COUNTRY_INFO as BZ_COUNTRY } from './bz-tin';
import { validateCATIN, TIN_INFO as CA_INFO, TIN_REQUIREMENTS as CA_REQUIREMENTS, COUNTRY_INFO as CA_COUNTRY } from './ca-tin';
import { validateCDTIN, TIN_INFO as CD_INFO, TIN_REQUIREMENTS as CD_REQUIREMENTS, COUNTRY_INFO as CD_COUNTRY } from './cd-tin';
import { validateCFTIN, TIN_INFO as CF_INFO, TIN_REQUIREMENTS as CF_REQUIREMENTS, COUNTRY_INFO as CF_COUNTRY } from './cf-tin';
import { validateCGTIN, TIN_INFO as CG_INFO, TIN_REQUIREMENTS as CG_REQUIREMENTS, COUNTRY_INFO as CG_COUNTRY } from './cg-tin';
import { validateCHTIN, TIN_INFO as CH_INFO, TIN_REQUIREMENTS as CH_REQUIREMENTS, COUNTRY_INFO as CH_COUNTRY } from './ch-tin';
import { validateCITIN, TIN_INFO as CI_INFO, TIN_REQUIREMENTS as CI_REQUIREMENTS, COUNTRY_INFO as CI_COUNTRY } from './ci-tin';
import { validateCKTIN, TIN_INFO as CK_INFO, TIN_REQUIREMENTS as CK_REQUIREMENTS, COUNTRY_INFO as CK_COUNTRY } from './ck-tin';
import { validateCLTIN, TIN_INFO as CL_INFO, TIN_REQUIREMENTS as CL_REQUIREMENTS, COUNTRY_INFO as CL_COUNTRY } from './cl-tin';
import { validateCMTIN, TIN_INFO as CM_INFO, TIN_REQUIREMENTS as CM_REQUIREMENTS, COUNTRY_INFO as CM_COUNTRY } from './cm-tin';
import { validateCNTIN, TIN_INFO as CN_INFO, TIN_REQUIREMENTS as CN_REQUIREMENTS, COUNTRY_INFO as CN_COUNTRY } from './cn-tin';
import { validateCOTIN, TIN_INFO as CO_INFO, TIN_REQUIREMENTS as CO_REQUIREMENTS, COUNTRY_INFO as CO_COUNTRY } from './co-tin';
import { validateCRTIN, TIN_INFO as CR_INFO, TIN_REQUIREMENTS as CR_REQUIREMENTS, COUNTRY_INFO as CR_COUNTRY } from './cr-tin';
import { validateCUTIN, TIN_INFO as CU_INFO, TIN_REQUIREMENTS as CU_REQUIREMENTS, COUNTRY_INFO as CU_COUNTRY } from './cu-tin';
import { validateCVTIN, TIN_INFO as CV_INFO, TIN_REQUIREMENTS as CV_REQUIREMENTS, COUNTRY_INFO as CV_COUNTRY } from './cv-tin';
import { validateCWTIN, TIN_INFO as CW_INFO, TIN_REQUIREMENTS as CW_REQUIREMENTS, COUNTRY_INFO as CW_COUNTRY } from './cw-tin';
import { validateCYTIN, TIN_INFO as CY_INFO, TIN_REQUIREMENTS as CY_REQUIREMENTS, COUNTRY_INFO as CY_COUNTRY } from './cy-tin';
import { validateCZTIN, TIN_INFO as CZ_INFO, TIN_REQUIREMENTS as CZ_REQUIREMENTS, COUNTRY_INFO as CZ_COUNTRY } from './cz-tin';
import { validateDETIN, TIN_INFO as DE_INFO, TIN_REQUIREMENTS as DE_REQUIREMENTS, COUNTRY_INFO as DE_COUNTRY } from './de-tin';
import { validateDJTIN, TIN_INFO as DJ_INFO, TIN_REQUIREMENTS as DJ_REQUIREMENTS, COUNTRY_INFO as DJ_COUNTRY } from './dj-tin';
import { validateDKTIN, TIN_INFO as DK_INFO, TIN_REQUIREMENTS as DK_REQUIREMENTS, COUNTRY_INFO as DK_COUNTRY } from './dk-tin';
import { validateDOTIN, TIN_INFO as DO_INFO, TIN_REQUIREMENTS as DO_REQUIREMENTS, COUNTRY_INFO as DO_COUNTRY } from './do-tin';
import { validateDZTIN, TIN_INFO as DZ_INFO, TIN_REQUIREMENTS as DZ_REQUIREMENTS, COUNTRY_INFO as DZ_COUNTRY } from './dz-tin';
import { validateECTIN, TIN_INFO as EC_INFO, TIN_REQUIREMENTS as EC_REQUIREMENTS, COUNTRY_INFO as EC_COUNTRY } from './ec-tin';
import { validateEETIN, TIN_INFO as EE_INFO, TIN_REQUIREMENTS as EE_REQUIREMENTS, COUNTRY_INFO as EE_COUNTRY } from './ee-tin';
import { validateEGTIN, TIN_INFO as EG_INFO, TIN_REQUIREMENTS as EG_REQUIREMENTS, COUNTRY_INFO as EG_COUNTRY } from './eg-tin';
import { validateERTIN, TIN_INFO as ER_INFO, TIN_REQUIREMENTS as ER_REQUIREMENTS, COUNTRY_INFO as ER_COUNTRY } from './er-tin';
import { validateESTIN, TIN_INFO as ES_INFO, TIN_REQUIREMENTS as ES_REQUIREMENTS, COUNTRY_INFO as ES_COUNTRY } from './es-tin';
import { validateETTIN, TIN_INFO as ET_INFO, TIN_REQUIREMENTS as ET_REQUIREMENTS, COUNTRY_INFO as ET_COUNTRY } from './et-tin';
import { validateFITIN, TIN_INFO as FI_INFO, TIN_REQUIREMENTS as FI_REQUIREMENTS, COUNTRY_INFO as FI_COUNTRY } from './fi-tin';
import { validateFJTIN, TIN_INFO as FJ_INFO, TIN_REQUIREMENTS as FJ_REQUIREMENTS, COUNTRY_INFO as FJ_COUNTRY } from './fj-tin';
import { validateFOTIN, TIN_INFO as FO_INFO, TIN_REQUIREMENTS as FO_REQUIREMENTS, COUNTRY_INFO as FO_COUNTRY } from './fo-tin';
import { validateFRTIN, TIN_INFO as FR_INFO, TIN_REQUIREMENTS as FR_REQUIREMENTS, COUNTRY_INFO as FR_COUNTRY } from './fr-tin';
import { validateGATIN, TIN_INFO as GA_INFO, TIN_REQUIREMENTS as GA_REQUIREMENTS, COUNTRY_INFO as GA_COUNTRY } from './ga-tin';
import { validateGBTIN, TIN_INFO as GB_INFO, TIN_REQUIREMENTS as GB_REQUIREMENTS, COUNTRY_INFO as GB_COUNTRY } from './gb-tin';
import { validateGDTIN, TIN_INFO as GD_INFO, TIN_REQUIREMENTS as GD_REQUIREMENTS, COUNTRY_INFO as GD_COUNTRY } from './gd-tin';
import { validateGETIN, TIN_INFO as GE_INFO, TIN_REQUIREMENTS as GE_REQUIREMENTS, COUNTRY_INFO as GE_COUNTRY } from './ge-tin';
import { validateGGTIN, TIN_INFO as GG_INFO, TIN_REQUIREMENTS as GG_REQUIREMENTS, COUNTRY_INFO as GG_COUNTRY } from './gg-tin';
import { validateGHTIN, TIN_INFO as GH_INFO, TIN_REQUIREMENTS as GH_REQUIREMENTS, COUNTRY_INFO as GH_COUNTRY } from './gh-tin';
import { validateGITIN, TIN_INFO as GI_INFO, TIN_REQUIREMENTS as GI_REQUIREMENTS, COUNTRY_INFO as GI_COUNTRY } from './gi-tin';
import { validateGLTIN, TIN_INFO as GL_INFO, TIN_REQUIREMENTS as GL_REQUIREMENTS, COUNTRY_INFO as GL_COUNTRY } from './gl-tin';
import { validateGMTIN, TIN_INFO as GM_INFO, TIN_REQUIREMENTS as GM_REQUIREMENTS, COUNTRY_INFO as GM_COUNTRY } from './gm-tin';
import { validateGNTIN, TIN_INFO as GN_INFO, TIN_REQUIREMENTS as GN_REQUIREMENTS, COUNTRY_INFO as GN_COUNTRY } from './gn-tin';
import { validateGQTIN, TIN_INFO as GQ_INFO, TIN_REQUIREMENTS as GQ_REQUIREMENTS, COUNTRY_INFO as GQ_COUNTRY } from './gq-tin';
import { validateGRTIN, TIN_INFO as GR_INFO, TIN_REQUIREMENTS as GR_REQUIREMENTS, COUNTRY_INFO as GR_COUNTRY } from './gr-tin';
import { validateGTTIN, TIN_INFO as GT_INFO, TIN_REQUIREMENTS as GT_REQUIREMENTS, COUNTRY_INFO as GT_COUNTRY } from './gt-tin';
import { validateGWTIN, TIN_INFO as GW_INFO, TIN_REQUIREMENTS as GW_REQUIREMENTS, COUNTRY_INFO as GW_COUNTRY } from './gw-tin';
import { validateGYTIN, TIN_INFO as GY_INFO, TIN_REQUIREMENTS as GY_REQUIREMENTS, COUNTRY_INFO as GY_COUNTRY } from './gy-tin';
import { validateHKTIN, TIN_INFO as HK_INFO, TIN_REQUIREMENTS as HK_REQUIREMENTS, COUNTRY_INFO as HK_COUNTRY } from './hk-tin';
import { validateHNTIN, TIN_INFO as HN_INFO, TIN_REQUIREMENTS as HN_REQUIREMENTS, COUNTRY_INFO as HN_COUNTRY } from './hn-tin';
import { validateHRTIN, TIN_INFO as HR_INFO, TIN_REQUIREMENTS as HR_REQUIREMENTS, COUNTRY_INFO as HR_COUNTRY } from './hr-tin';
import { validateHTTIN, TIN_INFO as HT_INFO, TIN_REQUIREMENTS as HT_REQUIREMENTS, COUNTRY_INFO as HT_COUNTRY } from './ht-tin';
import { validateHUTIN, TIN_INFO as HU_INFO, TIN_REQUIREMENTS as HU_REQUIREMENTS, COUNTRY_INFO as HU_COUNTRY } from './hu-tin';
import { validateIDTIN, TIN_INFO as ID_INFO, TIN_REQUIREMENTS as ID_REQUIREMENTS, COUNTRY_INFO as ID_COUNTRY } from './id-tin';
import { validateIETIN, TIN_INFO as IE_INFO, TIN_REQUIREMENTS as IE_REQUIREMENTS, COUNTRY_INFO as IE_COUNTRY } from './ie-tin';
import { validateILTIN, TIN_INFO as IL_INFO, TIN_REQUIREMENTS as IL_REQUIREMENTS, COUNTRY_INFO as IL_COUNTRY } from './il-tin';
import { validateIMTIN, TIN_INFO as IM_INFO, TIN_REQUIREMENTS as IM_REQUIREMENTS, COUNTRY_INFO as IM_COUNTRY } from './im-tin';
import { validateINTIN, TIN_INFO as IN_INFO, TIN_REQUIREMENTS as IN_REQUIREMENTS, COUNTRY_INFO as IN_COUNTRY } from './in-tin';
import { validateIQTIN, TIN_INFO as IQ_INFO, TIN_REQUIREMENTS as IQ_REQUIREMENTS, COUNTRY_INFO as IQ_COUNTRY } from './iq-tin';
import { validateIRTIN, TIN_INFO as IR_INFO, TIN_REQUIREMENTS as IR_REQUIREMENTS, COUNTRY_INFO as IR_COUNTRY } from './ir-tin';
import { validateISTIN, TIN_INFO as IS_INFO, TIN_REQUIREMENTS as IS_REQUIREMENTS, COUNTRY_INFO as IS_COUNTRY } from './is-tin';
import { validateITTIN, TIN_INFO as IT_INFO, TIN_REQUIREMENTS as IT_REQUIREMENTS, COUNTRY_INFO as IT_COUNTRY } from './it-tin';
import { validateJETIN, TIN_INFO as JE_INFO, TIN_REQUIREMENTS as JE_REQUIREMENTS, COUNTRY_INFO as JE_COUNTRY } from './je-tin';
import { validateJMTIN, TIN_INFO as JM_INFO, TIN_REQUIREMENTS as JM_REQUIREMENTS, COUNTRY_INFO as JM_COUNTRY } from './jm-tin';
import { validateJOTIN, TIN_INFO as JO_INFO, TIN_REQUIREMENTS as JO_REQUIREMENTS, COUNTRY_INFO as JO_COUNTRY } from './jo-tin';
import { validateJPTIN, TIN_INFO as JP_INFO, TIN_REQUIREMENTS as JP_REQUIREMENTS, COUNTRY_INFO as JP_COUNTRY } from './jp-tin';
import { validateKETIN, TIN_INFO as KE_INFO, TIN_REQUIREMENTS as KE_REQUIREMENTS, COUNTRY_INFO as KE_COUNTRY } from './ke-tin';
import { validateKGTIN, TIN_INFO as KG_INFO, TIN_REQUIREMENTS as KG_REQUIREMENTS, COUNTRY_INFO as KG_COUNTRY } from './kg-tin';
import { validateKHTIN, TIN_INFO as KH_INFO, TIN_REQUIREMENTS as KH_REQUIREMENTS, COUNTRY_INFO as KH_COUNTRY } from './kh-tin';
import { validateKITIN, TIN_INFO as KI_INFO, TIN_REQUIREMENTS as KI_REQUIREMENTS, COUNTRY_INFO as KI_COUNTRY } from './ki-tin';
import { validateKMTIN, TIN_INFO as KM_INFO, TIN_REQUIREMENTS as KM_REQUIREMENTS, COUNTRY_INFO as KM_COUNTRY } from './km-tin';
import { validateKRTIN as validateKRTIN_Orig, TIN_INFO as KR_INFO, TIN_REQUIREMENTS as KR_REQUIREMENTS, COUNTRY_INFO as KR_COUNTRY } from './kr-tin';
import { validateKWTIN, TIN_INFO as KW_INFO, TIN_REQUIREMENTS as KW_REQUIREMENTS, COUNTRY_INFO as KW_COUNTRY } from './kw-tin';
import { validateKZTIN, TIN_INFO as KZ_INFO, TIN_REQUIREMENTS as KZ_REQUIREMENTS, COUNTRY_INFO as KZ_COUNTRY } from './kz-tin';
import { validateLATIN, TIN_INFO as LA_INFO, TIN_REQUIREMENTS as LA_REQUIREMENTS, COUNTRY_INFO as LA_COUNTRY } from './la-tin';
import { validateLBTIN, TIN_INFO as LB_INFO, TIN_REQUIREMENTS as LB_REQUIREMENTS, COUNTRY_INFO as LB_COUNTRY } from './lb-tin';
import { validateLCTIN, TIN_INFO as LC_INFO, TIN_REQUIREMENTS as LC_REQUIREMENTS, COUNTRY_INFO as LC_COUNTRY } from './lc-tin';
import { validateLITIN, TIN_INFO as LI_INFO, TIN_REQUIREMENTS as LI_REQUIREMENTS, COUNTRY_INFO as LI_COUNTRY } from './li-tin';
import { validateLKTIN, TIN_INFO as LK_INFO, TIN_REQUIREMENTS as LK_REQUIREMENTS, COUNTRY_INFO as LK_COUNTRY } from './lk-tin';
import { validateLRTIN, TIN_INFO as LR_INFO, TIN_REQUIREMENTS as LR_REQUIREMENTS, COUNTRY_INFO as LR_COUNTRY } from './lr-tin';
import { validateLSTIN, TIN_INFO as LS_INFO, TIN_REQUIREMENTS as LS_REQUIREMENTS, COUNTRY_INFO as LS_COUNTRY } from './ls-tin';
import { validateLTTIN, TIN_INFO as LT_INFO, TIN_REQUIREMENTS as LT_REQUIREMENTS, COUNTRY_INFO as LT_COUNTRY } from './lt-tin';
import { validateLUTIN, TIN_INFO as LU_INFO, TIN_REQUIREMENTS as LU_REQUIREMENTS, COUNTRY_INFO as LU_COUNTRY } from './lu-tin';
import { validateLVTIN, TIN_INFO as LV_INFO, TIN_REQUIREMENTS as LV_REQUIREMENTS, COUNTRY_INFO as LV_COUNTRY } from './lv-tin';
import { validateLYTIN, TIN_INFO as LY_INFO, TIN_REQUIREMENTS as LY_REQUIREMENTS, COUNTRY_INFO as LY_COUNTRY } from './ly-tin';
import { validateMATIN, TIN_INFO as MA_INFO, TIN_REQUIREMENTS as MA_REQUIREMENTS, COUNTRY_INFO as MA_COUNTRY } from './ma-tin';
import { validateMDTIN, TIN_INFO as MD_INFO, TIN_REQUIREMENTS as MD_REQUIREMENTS, COUNTRY_INFO as MD_COUNTRY } from './md-tin';
import { validateMETIN, TIN_INFO as ME_INFO, TIN_REQUIREMENTS as ME_REQUIREMENTS, COUNTRY_INFO as ME_COUNTRY } from './me-tin';
import { validateMGTIN, TIN_INFO as MG_INFO, TIN_REQUIREMENTS as MG_REQUIREMENTS, COUNTRY_INFO as MG_COUNTRY } from './mg-tin';
import { validateMHTIN, TIN_INFO as MH_INFO, TIN_REQUIREMENTS as MH_REQUIREMENTS, COUNTRY_INFO as MH_COUNTRY } from './mh-tin';
import { validateMKTIN, TIN_INFO as MK_INFO, TIN_REQUIREMENTS as MK_REQUIREMENTS, COUNTRY_INFO as MK_COUNTRY } from './mk-tin';
import { validateMLTIN, TIN_INFO as ML_INFO, TIN_REQUIREMENTS as ML_REQUIREMENTS, COUNTRY_INFO as ML_COUNTRY } from './ml-tin';
import { validateMMTIN, TIN_INFO as MM_INFO, TIN_REQUIREMENTS as MM_REQUIREMENTS, COUNTRY_INFO as MM_COUNTRY } from './mm-tin';
import { validateMNTIN, TIN_INFO as MN_INFO, TIN_REQUIREMENTS as MN_REQUIREMENTS, COUNTRY_INFO as MN_COUNTRY } from './mn-tin';
import { validateMOTIN, TIN_INFO as MO_INFO, TIN_REQUIREMENTS as MO_REQUIREMENTS, COUNTRY_INFO as MO_COUNTRY } from './mo-tin';
import { validateMRTIN, TIN_INFO as MR_INFO, TIN_REQUIREMENTS as MR_REQUIREMENTS, COUNTRY_INFO as MR_COUNTRY } from './mr-tin';
import { validateMTTIN, TIN_INFO as MT_INFO, TIN_REQUIREMENTS as MT_REQUIREMENTS, COUNTRY_INFO as MT_COUNTRY } from './mt-tin';
import { validateMUTIN, TIN_INFO as MU_INFO, TIN_REQUIREMENTS as MU_REQUIREMENTS, COUNTRY_INFO as MU_COUNTRY } from './mu-tin';
import { validateMVTIN, TIN_INFO as MV_INFO, TIN_REQUIREMENTS as MV_REQUIREMENTS, COUNTRY_INFO as MV_COUNTRY } from './mv-tin';
import { validateMWTIN, TIN_INFO as MW_INFO, TIN_REQUIREMENTS as MW_REQUIREMENTS, COUNTRY_INFO as MW_COUNTRY } from './mw-tin';
import { validateMXTIN, TIN_INFO as MX_INFO, TIN_REQUIREMENTS as MX_REQUIREMENTS, COUNTRY_INFO as MX_COUNTRY } from './mx-tin';
import { validateMYTIN, TIN_INFO as MY_INFO, TIN_REQUIREMENTS as MY_REQUIREMENTS, COUNTRY_INFO as MY_COUNTRY } from './my-tin';
import { validateMZTIN, TIN_INFO as MZ_INFO, TIN_REQUIREMENTS as MZ_REQUIREMENTS, COUNTRY_INFO as MZ_COUNTRY } from './mz-tin';
import { validateNATIN, TIN_INFO as NA_INFO, TIN_REQUIREMENTS as NA_REQUIREMENTS, COUNTRY_INFO as NA_COUNTRY } from './na-tin';
import { validateNETIN, TIN_INFO as NE_INFO, TIN_REQUIREMENTS as NE_REQUIREMENTS, COUNTRY_INFO as NE_COUNTRY } from './ne-tin';
import { validateNGTIN, TIN_INFO as NG_INFO, TIN_REQUIREMENTS as NG_REQUIREMENTS, COUNTRY_INFO as NG_COUNTRY } from './ng-tin';
import { validateNITIN, TIN_INFO as NI_INFO, TIN_REQUIREMENTS as NI_REQUIREMENTS, COUNTRY_INFO as NI_COUNTRY } from './ni-tin';
import { validateNLTIN, TIN_INFO as NL_INFO, TIN_REQUIREMENTS as NL_REQUIREMENTS, COUNTRY_INFO as NL_COUNTRY } from './nl-tin';
import { validateNOTIN, TIN_INFO as NO_INFO, TIN_REQUIREMENTS as NO_REQUIREMENTS, COUNTRY_INFO as NO_COUNTRY } from './no-tin';
import { validateNPTIN, TIN_INFO as NP_INFO, TIN_REQUIREMENTS as NP_REQUIREMENTS, COUNTRY_INFO as NP_COUNTRY } from './np-tin';
import { validateNRTIN, TIN_INFO as NR_INFO, TIN_REQUIREMENTS as NR_REQUIREMENTS, COUNTRY_INFO as NR_COUNTRY } from './nr-tin';
import { validateNUTIN, TIN_INFO as NU_INFO, TIN_REQUIREMENTS as NU_REQUIREMENTS, COUNTRY_INFO as NU_COUNTRY } from './nu-tin';
import { validateNZTIN, TIN_INFO as NZ_INFO, TIN_REQUIREMENTS as NZ_REQUIREMENTS, COUNTRY_INFO as NZ_COUNTRY } from './nz-tin';
import { validateOMTIN, TIN_INFO as OM_INFO, TIN_REQUIREMENTS as OM_REQUIREMENTS, COUNTRY_INFO as OM_COUNTRY } from './om-tin';
import { validatePATIN, TIN_INFO as PA_INFO, TIN_REQUIREMENTS as PA_REQUIREMENTS, COUNTRY_INFO as PA_COUNTRY } from './pa-tin';
import { validatePETIN, TIN_INFO as PE_INFO, TIN_REQUIREMENTS as PE_REQUIREMENTS, COUNTRY_INFO as PE_COUNTRY } from './pe-tin';
import { validatePGTIN, TIN_INFO as PG_INFO, TIN_REQUIREMENTS as PG_REQUIREMENTS, COUNTRY_INFO as PG_COUNTRY } from './pg-tin';
import { validatePHTIN, TIN_INFO as PH_INFO, TIN_REQUIREMENTS as PH_REQUIREMENTS, COUNTRY_INFO as PH_COUNTRY } from './ph-tin';
import { validatePKTIN, TIN_INFO as PK_INFO, TIN_REQUIREMENTS as PK_REQUIREMENTS, COUNTRY_INFO as PK_COUNTRY } from './pk-tin';
import { validatePLTIN, TIN_INFO as PL_INFO, TIN_REQUIREMENTS as PL_REQUIREMENTS, COUNTRY_INFO as PL_COUNTRY } from './pl-tin';
import { validatePSTIN, TIN_INFO as PS_INFO, TIN_REQUIREMENTS as PS_REQUIREMENTS, COUNTRY_INFO as PS_COUNTRY } from './ps-tin';
import { validatePTTIN, TIN_INFO as PT_INFO, TIN_REQUIREMENTS as PT_REQUIREMENTS, COUNTRY_INFO as PT_COUNTRY } from './pt-tin';
import { validatePYTIN, TIN_INFO as PY_INFO, TIN_REQUIREMENTS as PY_REQUIREMENTS, COUNTRY_INFO as PY_COUNTRY } from './py-tin';
import { validateQATIN, TIN_INFO as QA_INFO, TIN_REQUIREMENTS as QA_REQUIREMENTS, COUNTRY_INFO as QA_COUNTRY } from './qa-tin';
import { validateROTIN, TIN_INFO as RO_INFO, TIN_REQUIREMENTS as RO_REQUIREMENTS, COUNTRY_INFO as RO_COUNTRY } from './ro-tin';
import { validateRSTIN, TIN_INFO as RS_INFO, TIN_REQUIREMENTS as RS_REQUIREMENTS, COUNTRY_INFO as RS_COUNTRY } from './rs-tin';
import { validateRUTIN, TIN_INFO as RU_INFO, TIN_REQUIREMENTS as RU_REQUIREMENTS, COUNTRY_INFO as RU_COUNTRY } from './ru-tin';
import { validateRWTIN, TIN_INFO as RW_INFO, TIN_REQUIREMENTS as RW_REQUIREMENTS, COUNTRY_INFO as RW_COUNTRY } from './rw-tin';
import { validateSATIN, TIN_INFO as SA_INFO, TIN_REQUIREMENTS as SA_REQUIREMENTS, COUNTRY_INFO as SA_COUNTRY } from './sa-tin';
import { validateSBTIN, TIN_INFO as SB_INFO, TIN_REQUIREMENTS as SB_REQUIREMENTS, COUNTRY_INFO as SB_COUNTRY } from './sb-tin';
import { validateSCTIN, TIN_INFO as SC_INFO, TIN_REQUIREMENTS as SC_REQUIREMENTS, COUNTRY_INFO as SC_COUNTRY } from './sc-tin';
import { validateSDTIN, TIN_INFO as SD_INFO, TIN_REQUIREMENTS as SD_REQUIREMENTS, COUNTRY_INFO as SD_COUNTRY } from './sd-tin';
import { validateSETIN, TIN_INFO as SE_INFO, TIN_REQUIREMENTS as SE_REQUIREMENTS, COUNTRY_INFO as SE_COUNTRY } from './se-tin';
import { validateSGTIN, TIN_INFO as SG_INFO, TIN_REQUIREMENTS as SG_REQUIREMENTS, COUNTRY_INFO as SG_COUNTRY } from './sg-tin';
import { validateSITIN, TIN_INFO as SI_INFO, TIN_REQUIREMENTS as SI_REQUIREMENTS, COUNTRY_INFO as SI_COUNTRY } from './si-tin';
import { validateSKTIN, TIN_INFO as SK_INFO, TIN_REQUIREMENTS as SK_REQUIREMENTS, COUNTRY_INFO as SK_COUNTRY } from './sk-tin';
import { validateSLTIN, TIN_INFO as SL_INFO, TIN_REQUIREMENTS as SL_REQUIREMENTS, COUNTRY_INFO as SL_COUNTRY } from './sl-tin';
import { validateSMTIN, TIN_INFO as SM_INFO, TIN_REQUIREMENTS as SM_REQUIREMENTS, COUNTRY_INFO as SM_COUNTRY } from './sm-tin';
import { validateSNTIN, TIN_INFO as SN_INFO, TIN_REQUIREMENTS as SN_REQUIREMENTS, COUNTRY_INFO as SN_COUNTRY } from './sn-tin';
import { validateSOTIN, TIN_INFO as SO_INFO, TIN_REQUIREMENTS as SO_REQUIREMENTS, COUNTRY_INFO as SO_COUNTRY } from './so-tin';
import { validateSRTIN, TIN_INFO as SR_INFO, TIN_REQUIREMENTS as SR_REQUIREMENTS, COUNTRY_INFO as SR_COUNTRY } from './sr-tin';
import { validateSSTIN, TIN_INFO as SS_INFO, TIN_REQUIREMENTS as SS_REQUIREMENTS, COUNTRY_INFO as SS_COUNTRY } from './ss-tin';
import { validateSTTIN, TIN_INFO as ST_INFO, TIN_REQUIREMENTS as ST_REQUIREMENTS, COUNTRY_INFO as ST_COUNTRY } from './st-tin';
import { validateSVTIN, TIN_INFO as SV_INFO, TIN_REQUIREMENTS as SV_REQUIREMENTS, COUNTRY_INFO as SV_COUNTRY } from './sv-tin';
import { validateSXTIN, TIN_INFO as SX_INFO, TIN_REQUIREMENTS as SX_REQUIREMENTS, COUNTRY_INFO as SX_COUNTRY } from './sx-tin';
import { validateSYTIN, TIN_INFO as SY_INFO, TIN_REQUIREMENTS as SY_REQUIREMENTS, COUNTRY_INFO as SY_COUNTRY } from './sy-tin';
import { validateSZTIN, TIN_INFO as SZ_INFO, TIN_REQUIREMENTS as SZ_REQUIREMENTS, COUNTRY_INFO as SZ_COUNTRY } from './sz-tin';
import { validateTDTIN, TIN_INFO as TD_INFO, TIN_REQUIREMENTS as TD_REQUIREMENTS, COUNTRY_INFO as TD_COUNTRY } from './td-tin';
import { validateTGTIN, TIN_INFO as TG_INFO, TIN_REQUIREMENTS as TG_REQUIREMENTS, COUNTRY_INFO as TG_COUNTRY } from './tg-tin';
import { validateTHTIN, TIN_INFO as TH_INFO, TIN_REQUIREMENTS as TH_REQUIREMENTS, COUNTRY_INFO as TH_COUNTRY } from './th-tin';
import { validateTJTIN, TIN_INFO as TJ_INFO, TIN_REQUIREMENTS as TJ_REQUIREMENTS, COUNTRY_INFO as TJ_COUNTRY } from './tj-tin';
import { validateTLTIN, TIN_INFO as TL_INFO, TIN_REQUIREMENTS as TL_REQUIREMENTS, COUNTRY_INFO as TL_COUNTRY } from './tl-tin';
import { validateTMTIN, TIN_INFO as TM_INFO, TIN_REQUIREMENTS as TM_REQUIREMENTS, COUNTRY_INFO as TM_COUNTRY } from './tm-tin';
import { validateTNTIN, TIN_INFO as TN_INFO, TIN_REQUIREMENTS as TN_REQUIREMENTS, COUNTRY_INFO as TN_COUNTRY } from './tn-tin';
import { validateTOTIN, TIN_INFO as TO_INFO, TIN_REQUIREMENTS as TO_REQUIREMENTS, COUNTRY_INFO as TO_COUNTRY } from './to-tin';
import { validateTRTIN, TIN_INFO as TR_INFO, TIN_REQUIREMENTS as TR_REQUIREMENTS, COUNTRY_INFO as TR_COUNTRY } from './tr-tin';
import { validateTTTIN, TIN_INFO as TT_INFO, TIN_REQUIREMENTS as TT_REQUIREMENTS, COUNTRY_INFO as TT_COUNTRY } from './tt-tin';
import { validateTVTIN, TIN_INFO as TV_INFO, TIN_REQUIREMENTS as TV_REQUIREMENTS, COUNTRY_INFO as TV_COUNTRY } from './tv-tin';
import { validateTWTIN, TIN_INFO as TW_INFO, TIN_REQUIREMENTS as TW_REQUIREMENTS, COUNTRY_INFO as TW_COUNTRY } from './tw-tin';
import { validateTZTIN, TIN_INFO as TZ_INFO, TIN_REQUIREMENTS as TZ_REQUIREMENTS, COUNTRY_INFO as TZ_COUNTRY } from './tz-tin';
import { validateUATIN, TIN_INFO as UA_INFO, TIN_REQUIREMENTS as UA_REQUIREMENTS, COUNTRY_INFO as UA_COUNTRY } from './ua-tin';
import { validateUGTIN, TIN_INFO as UG_INFO, TIN_REQUIREMENTS as UG_REQUIREMENTS, COUNTRY_INFO as UG_COUNTRY } from './ug-tin';
import { validateUSTIN, TIN_INFO as US_INFO, TIN_REQUIREMENTS as US_REQUIREMENTS, COUNTRY_INFO as US_COUNTRY } from './us-tin';
import { validateUYTIN, TIN_INFO as UY_INFO, TIN_REQUIREMENTS as UY_REQUIREMENTS, COUNTRY_INFO as UY_COUNTRY } from './uy-tin';
import { validateUZTIN, TIN_INFO as UZ_INFO, TIN_REQUIREMENTS as UZ_REQUIREMENTS, COUNTRY_INFO as UZ_COUNTRY } from './uz-tin';
import { validateVATIN, TIN_INFO as VA_INFO, TIN_REQUIREMENTS as VA_REQUIREMENTS, COUNTRY_INFO as VA_COUNTRY } from './va-tin';
import { validateVCTIN, TIN_INFO as VC_INFO, TIN_REQUIREMENTS as VC_REQUIREMENTS, COUNTRY_INFO as VC_COUNTRY } from './vc-tin';
import { validateVETIN, TIN_INFO as VE_INFO, TIN_REQUIREMENTS as VE_REQUIREMENTS, COUNTRY_INFO as VE_COUNTRY } from './ve-tin';
import { validateVNTIN, TIN_INFO as VN_INFO, TIN_REQUIREMENTS as VN_REQUIREMENTS, COUNTRY_INFO as VN_COUNTRY } from './vn-tin';
import { validateVUTIN, TIN_INFO as VU_INFO, TIN_REQUIREMENTS as VU_REQUIREMENTS, COUNTRY_INFO as VU_COUNTRY } from './vu-tin';
import { validateWFTIN, TIN_INFO as WF_INFO, TIN_REQUIREMENTS as WF_REQUIREMENTS, COUNTRY_INFO as WF_COUNTRY } from './wf-tin';
import { validateWSTIN, TIN_INFO as WS_INFO, TIN_REQUIREMENTS as WS_REQUIREMENTS, COUNTRY_INFO as WS_COUNTRY } from './ws-tin';
import { validateXKTIN, TIN_INFO as XK_INFO, TIN_REQUIREMENTS as XK_REQUIREMENTS, COUNTRY_INFO as XK_COUNTRY } from './xk-tin';
import { validateYETIN, TIN_INFO as YE_INFO, TIN_REQUIREMENTS as YE_REQUIREMENTS, COUNTRY_INFO as YE_COUNTRY } from './ye-tin';
import { validateYTTIN, TIN_INFO as YT_INFO, TIN_REQUIREMENTS as YT_REQUIREMENTS, COUNTRY_INFO as YT_COUNTRY } from './yt-tin';
import { validateZATIN, TIN_INFO as ZA_INFO, TIN_REQUIREMENTS as ZA_REQUIREMENTS, COUNTRY_INFO as ZA_COUNTRY } from './za-tin';
import { validateZMTIN, TIN_INFO as ZM_INFO, TIN_REQUIREMENTS as ZM_REQUIREMENTS, COUNTRY_INFO as ZM_COUNTRY } from './zm-tin';
import { validateZWTIN, TIN_INFO as ZW_INFO, TIN_REQUIREMENTS as ZW_REQUIREMENTS, COUNTRY_INFO as ZW_COUNTRY } from './zw-tin';

// Missing imports to be checked/added if needed:
// DM, CK, NU, GD, SX... (I'll assume they follow the pattern)
import { validateDMTIN, TIN_INFO as DM_INFO, TIN_REQUIREMENTS as DM_REQUIREMENTS, COUNTRY_INFO as DM_COUNTRY } from './dm-tin';

// --- REGISTRY MAPS ---

export const REQUIREMENTS_MAP = buildRegistry({
    'AD': AD_REQUIREMENTS, 'AE': AE_REQUIREMENTS, 'AF': AF_REQUIREMENTS, 'AG': AG_REQUIREMENTS, 'AI': AI_REQUIREMENTS,
    'AL': AL_REQUIREMENTS, 'AM': AM_REQUIREMENTS, 'AO': AO_REQUIREMENTS, 'AR': AR_REQUIREMENTS,
    'AT': AT_REQUIREMENTS, 'AU': AU_REQUIREMENTS, 'AW': AW_REQUIREMENTS, 'AZ': AZ_REQUIREMENTS,
    'BA': BA_REQUIREMENTS, 'BB': BB_REQUIREMENTS, 'BD': BD_REQUIREMENTS, 'BE': BE_REQUIREMENTS,
    'BF': BF_REQUIREMENTS, 'BG': BG_REQUIREMENTS, 'BH': BH_REQUIREMENTS, 'BI': BI_REQUIREMENTS, 'BJ': BJ_REQUIREMENTS,
    'BN': BN_REQUIREMENTS, 'BO': BO_REQUIREMENTS, 'BQ': BQ_REQUIREMENTS, 'BR': BR_REQUIREMENTS,
    'BS': BS_REQUIREMENTS, 'BT': BT_REQUIREMENTS, 'BW': BW_REQUIREMENTS, 'BY': BY_REQUIREMENTS,
    'BZ': BZ_REQUIREMENTS, 'CA': CA_REQUIREMENTS, 'CD': CD_REQUIREMENTS, 'CF': CF_REQUIREMENTS,
    'CG': CG_REQUIREMENTS, 'CH': CH_REQUIREMENTS, 'CI': CI_REQUIREMENTS, 'CK': CK_REQUIREMENTS,
    'CL': CL_REQUIREMENTS, 'CM': CM_REQUIREMENTS, 'CN': CN_REQUIREMENTS, 'CO': CO_REQUIREMENTS,
    'CR': CR_REQUIREMENTS, 'CU': CU_REQUIREMENTS, 'CV': CV_REQUIREMENTS, 'CW': CW_REQUIREMENTS,
    'CY': CY_REQUIREMENTS, 'CZ': CZ_REQUIREMENTS, 'DE': DE_REQUIREMENTS, 'DJ': DJ_REQUIREMENTS,
    'DK': DK_REQUIREMENTS, 'DM': DM_REQUIREMENTS, 'DO': DO_REQUIREMENTS, 'DZ': DZ_REQUIREMENTS,
    'EC': EC_REQUIREMENTS, 'EE': EE_REQUIREMENTS, 'EG': EG_REQUIREMENTS, 'ER': ER_REQUIREMENTS,
    'ES': ES_REQUIREMENTS, 'ET': ET_REQUIREMENTS, 'FI': FI_REQUIREMENTS, 'FJ': FJ_REQUIREMENTS,
    'FO': FO_REQUIREMENTS, 'FR': FR_REQUIREMENTS, 'GA': GA_REQUIREMENTS, 'GB': GB_REQUIREMENTS,
    'GD': GD_REQUIREMENTS, 'GE': GE_REQUIREMENTS, 'GG': GG_REQUIREMENTS, 'GH': GH_REQUIREMENTS,
    'GI': GI_REQUIREMENTS, 'GL': GL_REQUIREMENTS, 'GM': GM_REQUIREMENTS, 'GN': GN_REQUIREMENTS,
    'GQ': GQ_REQUIREMENTS, 'GR': GR_REQUIREMENTS, 'GT': GT_REQUIREMENTS, 'GW': GW_REQUIREMENTS,
    'GY': GY_REQUIREMENTS, 'HK': HK_REQUIREMENTS, 'HN': HN_REQUIREMENTS, 'HR': HR_REQUIREMENTS,
    'HT': HT_REQUIREMENTS, 'HU': HU_REQUIREMENTS, 'ID': ID_REQUIREMENTS, 'IE': IE_REQUIREMENTS,
    'IL': IL_REQUIREMENTS, 'IM': IM_REQUIREMENTS, 'IN': IN_REQUIREMENTS, 'IQ': IQ_REQUIREMENTS,
    'IR': IR_REQUIREMENTS, 'IS': IS_REQUIREMENTS, 'IT': IT_REQUIREMENTS, 'JE': JE_REQUIREMENTS,
    'JM': JM_REQUIREMENTS, 'JO': JO_REQUIREMENTS, 'JP': JP_REQUIREMENTS, 'KE': KE_REQUIREMENTS,
    'KG': KG_REQUIREMENTS, 'KH': KH_REQUIREMENTS, 'KI': KI_REQUIREMENTS, 'KM': KM_REQUIREMENTS,
    'KR': KR_REQUIREMENTS, 'KW': KW_REQUIREMENTS, 'KZ': KZ_REQUIREMENTS, 'LA': LA_REQUIREMENTS,
    'LB': LB_REQUIREMENTS, 'LB_OLD': LB_REQUIREMENTS, 'LC': LC_REQUIREMENTS, 'LI': LI_REQUIREMENTS, 'LK': LK_REQUIREMENTS,
    'LR': LR_REQUIREMENTS, 'LS': LS_REQUIREMENTS, 'LT': LT_REQUIREMENTS, 'LU': LU_REQUIREMENTS,
    'LV': LV_REQUIREMENTS, 'LY': LY_REQUIREMENTS, 'MA': MA_REQUIREMENTS, 'MD': MD_REQUIREMENTS,
    'ME': ME_REQUIREMENTS, 'MG': MG_REQUIREMENTS, 'MH': MH_REQUIREMENTS, 'MK': MK_REQUIREMENTS,
    'ML': ML_REQUIREMENTS, 'MM': MM_REQUIREMENTS, 'MN': MN_REQUIREMENTS, 'MO': MO_REQUIREMENTS,
    'MR': MR_REQUIREMENTS, 'MT': MT_REQUIREMENTS, 'MU': MU_REQUIREMENTS, 'MV': MV_REQUIREMENTS,
    'MW': MW_REQUIREMENTS, 'MX': MX_REQUIREMENTS, 'MY': MY_REQUIREMENTS, 'MZ': MZ_REQUIREMENTS,
    'NA': NA_REQUIREMENTS, 'NE': NE_REQUIREMENTS, 'NG': NG_REQUIREMENTS, 'NI': NI_REQUIREMENTS,
    'NL': NL_REQUIREMENTS, 'NO': NO_REQUIREMENTS, 'NP': NP_REQUIREMENTS, 'NR': NR_REQUIREMENTS,
    'NU': NU_REQUIREMENTS, 'NZ': NZ_REQUIREMENTS, 'OM': OM_REQUIREMENTS, 'PA': PA_REQUIREMENTS,
    'PE': PE_REQUIREMENTS, 'PG': PG_REQUIREMENTS, 'PH': PH_REQUIREMENTS, 'PK': PK_REQUIREMENTS,
    'PL': PL_REQUIREMENTS, 'PS': PS_REQUIREMENTS, 'PT': PT_REQUIREMENTS, 'PY': PY_REQUIREMENTS,
    'QA': QA_REQUIREMENTS, 'RO': RO_REQUIREMENTS, 'RS': RS_REQUIREMENTS, 'RU': RU_REQUIREMENTS,
    'RW': RW_REQUIREMENTS, 'SA': SA_REQUIREMENTS, 'SB': SB_REQUIREMENTS, 'SC': SC_REQUIREMENTS,
    'SD': SD_REQUIREMENTS, 'SE': SE_REQUIREMENTS, 'SG': SG_REQUIREMENTS, 'SI': SI_REQUIREMENTS,
    'SK': SK_REQUIREMENTS, 'SL': SL_REQUIREMENTS, 'SM': SM_REQUIREMENTS, 'SN': SN_REQUIREMENTS,
    'SO': SO_REQUIREMENTS, 'SR': SR_REQUIREMENTS, 'SS': SS_REQUIREMENTS, 'ST': ST_REQUIREMENTS,
    'SV': SV_REQUIREMENTS, 'SX': SX_REQUIREMENTS, 'SY': SY_REQUIREMENTS, 'SZ': SZ_REQUIREMENTS,
    'TD': TD_REQUIREMENTS, 'TG': TG_REQUIREMENTS, 'TH': TH_REQUIREMENTS, 'TJ': TJ_REQUIREMENTS,
    'TL': TL_REQUIREMENTS, 'TM': TM_REQUIREMENTS, 'TN': TN_REQUIREMENTS, 'TO': TO_REQUIREMENTS,
    'TR': TR_REQUIREMENTS, 'TT': TT_REQUIREMENTS, 'TV': TV_REQUIREMENTS, 'TW': TW_REQUIREMENTS,
    'TZ': TZ_REQUIREMENTS, 'UA': UA_REQUIREMENTS, 'UG': UG_REQUIREMENTS, 'US': US_REQUIREMENTS,
    'UY': UY_REQUIREMENTS, 'UZ': UZ_REQUIREMENTS, 'VA': VA_REQUIREMENTS, 'VC': VC_REQUIREMENTS, 'VE': VE_REQUIREMENTS,
    'VN': VN_REQUIREMENTS, 'VU': VU_REQUIREMENTS, 'WF': WF_REQUIREMENTS, 'WS': WS_REQUIREMENTS, 'XK': XK_REQUIREMENTS,
    'YE': YE_REQUIREMENTS, 'YT': YT_REQUIREMENTS, 'ZA': ZA_REQUIREMENTS, 'ZM': ZM_REQUIREMENTS, 'ZW': ZW_REQUIREMENTS
});

export const COUNTRY_INFO_MAP = buildRegistry({
    'AD': AD_COUNTRY, 'AE': AE_COUNTRY, 'AF': AF_COUNTRY, 'AG': AG_COUNTRY, 'AI': AI_COUNTRY, 'AL': AL_COUNTRY,
    'AM': AM_COUNTRY, 'AO': AO_COUNTRY, 'AR': AR_COUNTRY, 'AT': AT_COUNTRY, 'AU': AU_COUNTRY,
    'AW': AW_COUNTRY, 'AZ': AZ_COUNTRY, 'BA': BA_COUNTRY, 'BB': BB_COUNTRY, 'BD': BD_COUNTRY,
    'BE': BE_COUNTRY, 'BF': BF_COUNTRY, 'BG': BG_COUNTRY, 'BI': BI_COUNTRY, 'BJ': BJ_COUNTRY,
    'BN': BN_COUNTRY, 'BO': BO_COUNTRY, 'BQ': BQ_COUNTRY, 'BR': BR_COUNTRY, 'BS': BS_COUNTRY,
    'BT': BT_COUNTRY, 'BW': BW_COUNTRY, 'BY': BY_COUNTRY, 'BZ': BZ_COUNTRY, 'CA': CA_COUNTRY,
    'CD': CD_COUNTRY, 'CF': CF_COUNTRY, 'CG': CG_COUNTRY, 'CH': CH_COUNTRY, 'CI': CI_COUNTRY,
    'CK': CK_COUNTRY, 'CL': CL_COUNTRY, 'CM': CM_COUNTRY, 'CN': CN_COUNTRY, 'CO': CO_COUNTRY,
    'BH': BH_COUNTRY, 'CR': CR_COUNTRY, 'CU': CU_COUNTRY, 'CV': CV_COUNTRY, 'CW': CW_COUNTRY, 'CY': CY_COUNTRY,
    'CZ': CZ_COUNTRY, 'DE': DE_COUNTRY, 'DJ': DJ_COUNTRY, 'DK': DK_COUNTRY, 'DM': DM_COUNTRY,
    'DO': DO_COUNTRY, 'DZ': DZ_COUNTRY, 'EC': EC_COUNTRY, 'EE': EE_COUNTRY, 'EG': EG_COUNTRY,
    'ER': ER_COUNTRY, 'ES': ES_COUNTRY, 'ET': ET_COUNTRY, 'FI': FI_COUNTRY, 'FJ': FJ_COUNTRY,
    'FO': FO_COUNTRY, 'FR': FR_COUNTRY, 'GA': GA_COUNTRY, 'GB': GB_COUNTRY, 'GD': GD_COUNTRY,
    'GE': GE_COUNTRY, 'GG': GG_COUNTRY, 'GH': GH_COUNTRY, 'GI': GI_COUNTRY, 'GL': GL_COUNTRY,
    'GM': GM_COUNTRY, 'GN': GN_COUNTRY, 'GQ': GQ_COUNTRY, 'GR': GR_COUNTRY, 'GT': GT_COUNTRY,
    'GW': GW_COUNTRY, 'GY': GY_COUNTRY, 'HK': HK_COUNTRY, 'HN': HN_COUNTRY, 'HR': HR_COUNTRY,
    'HT': HT_COUNTRY, 'HU': HU_COUNTRY, 'ID': ID_COUNTRY, 'IE': IE_COUNTRY, 'IL': IL_COUNTRY,
    'IM': IM_COUNTRY, 'IN': IN_COUNTRY, 'IQ': IQ_COUNTRY, 'IR': IR_COUNTRY, 'IS': IS_COUNTRY,
    'IT': IT_COUNTRY, 'JE': JE_COUNTRY, 'JM': JM_COUNTRY, 'JO': JO_COUNTRY, 'JP': JP_COUNTRY,
    'KE': KE_COUNTRY, 'KG': KG_COUNTRY, 'KH': KH_COUNTRY, 'KI': KI_COUNTRY, 'KM': KM_COUNTRY,
    'KR': KR_COUNTRY, 'KW': KW_COUNTRY, 'KZ': KZ_COUNTRY, 'LA': LA_COUNTRY, 'LB': LB_COUNTRY, 'LB_OLD': LB_COUNTRY,
    'LC': LC_COUNTRY, 'LI': LI_COUNTRY, 'LK': LK_COUNTRY, 'LR': LR_COUNTRY, 'LS': LS_COUNTRY,
    'LT': LT_COUNTRY, 'LU': LU_COUNTRY, 'LV': LV_COUNTRY, 'LY': LY_COUNTRY, 'MA': MA_COUNTRY,
    'MD': MD_COUNTRY, 'ME': ME_COUNTRY, 'MG': MG_COUNTRY, 'MH': MH_COUNTRY, 'MK': MK_COUNTRY,
    'ML': ML_COUNTRY, 'MM': MM_COUNTRY, 'MN': MN_COUNTRY, 'MO': MO_COUNTRY, 'MR': MR_COUNTRY,
    'MT': MT_COUNTRY, 'MU': MU_COUNTRY, 'MV': MV_COUNTRY, 'MW': MW_COUNTRY, 'MX': MX_COUNTRY,
    'MY': MY_COUNTRY, 'MZ': MZ_COUNTRY, 'NA': NA_COUNTRY, 'NE': NE_COUNTRY, 'NG': NG_COUNTRY,
    'NI': NI_COUNTRY, 'NL': NL_COUNTRY, 'NO': NO_COUNTRY, 'NP': NP_COUNTRY, 'NR': NR_COUNTRY,
    'NU': NU_COUNTRY, 'NZ': NZ_COUNTRY, 'OM': OM_COUNTRY, 'PA': PA_COUNTRY, 'PE': PE_COUNTRY,
    'PG': PG_COUNTRY, 'PH': PH_COUNTRY, 'PK': PK_COUNTRY, 'PL': PL_COUNTRY, 'PS': PS_COUNTRY,
    'PT': PT_COUNTRY, 'PY': PY_COUNTRY, 'QA': QA_COUNTRY, 'RO': RO_COUNTRY, 'RS': RS_COUNTRY,
    'RU': RU_COUNTRY, 'RW': RW_COUNTRY, 'SA': SA_COUNTRY, 'SB': SB_COUNTRY, 'SC': SC_COUNTRY,
    'SD': SD_COUNTRY, 'SE': SE_COUNTRY, 'SG': SG_COUNTRY, 'SI': SI_COUNTRY, 'SK': SK_COUNTRY,
    'SL': SL_COUNTRY, 'SM': SM_COUNTRY, 'SN': SN_COUNTRY, 'SO': SO_COUNTRY, 'SR': SR_COUNTRY,
    'SS': SS_COUNTRY, 'ST': ST_COUNTRY, 'SV': SV_COUNTRY, 'SX': SX_COUNTRY, 'SY': SY_COUNTRY,
    'SZ': SZ_COUNTRY, 'TD': TD_COUNTRY, 'TG': TG_COUNTRY, 'TH': TH_COUNTRY, 'TJ': TJ_COUNTRY,
    'TL': TL_COUNTRY, 'TM': TM_COUNTRY, 'TN': TN_COUNTRY, 'TO': TO_COUNTRY, 'TR': TR_COUNTRY,
    'TT': TT_COUNTRY, 'TV': TV_COUNTRY, 'TW': TW_COUNTRY, 'TZ': TZ_COUNTRY, 'UA': UA_COUNTRY,
    'UG': UG_COUNTRY, 'US': US_COUNTRY, 'UY': UY_COUNTRY, 'UZ': UZ_COUNTRY, 'VA': VA_COUNTRY, 'VC': VC_COUNTRY,
    'VE': VE_COUNTRY, 'VN': VN_COUNTRY, 'VU': VU_COUNTRY, 'WF': WF_COUNTRY, 'WS': WS_COUNTRY, 'XK': XK_COUNTRY,
    'YE': YE_COUNTRY, 'YT': YT_COUNTRY, 'ZA': ZA_COUNTRY, 'ZM': ZM_COUNTRY, 'ZW': ZW_COUNTRY
});

export const TIN_INFO_MAP = buildMetadataRegistryWithDescription({
    'AD': AD_INFO, 'AE': AE_INFO, 'AF': AF_INFO, 'AG': AG_INFO, 'AI': AI_INFO, 'AL': AL_INFO,
    'AM': AM_INFO, 'AO': AO_INFO, 'AR': AR_INFO, 'AT': AT_INFO, 'AU': AU_INFO,
    'AW': AW_INFO, 'AZ': AZ_INFO, 'BA': BA_INFO, 'BB': BB_INFO, 'BD': BD_INFO,
    'BE': BE_INFO, 'BF': BF_INFO, 'BG': BG_INFO, 'BI': BI_INFO, 'BJ': BJ_INFO,
    'BN': BN_INFO, 'BO': BO_INFO, 'BQ': BQ_INFO, 'BR': BR_INFO, 'BS': BS_INFO,
    'BT': BT_INFO, 'BW': BW_INFO, 'BY': BY_INFO, 'BZ': BZ_INFO, 'CA': CA_INFO,
    'CD': CD_INFO, 'CF': CF_INFO, 'CG': CG_INFO, 'CH': CH_INFO, 'CI': CI_INFO,
    'CK': CK_INFO, 'CL': CL_INFO, 'CM': CM_INFO, 'CN': CN_INFO, 'CO': CO_INFO,
    'CR': CR_INFO, 'CU': CU_INFO, 'CV': CV_INFO, 'CW': CW_INFO, 'CY': CY_INFO, 'BH': BH_INFO,
    'CZ': CZ_INFO, 'DE': DE_INFO, 'DJ': DJ_INFO, 'DK': DK_INFO, 'DM': DM_INFO,
    'DO': DO_INFO, 'DZ': DZ_INFO, 'EC': EC_INFO, 'EE': EE_INFO, 'EG': EG_INFO,
    'ER': ER_INFO, 'ES': ES_INFO, 'ET': ET_INFO, 'FI': FI_INFO, 'FJ': FJ_INFO,
    'FO': FO_INFO, 'FR': FR_INFO, 'GA': GA_INFO, 'GB': GB_INFO, 'GD': GD_INFO,
    'GE': GE_INFO, 'GG': GG_INFO, 'GH': GH_INFO, 'GI': GI_INFO, 'GL': GL_INFO,
    'GM': GM_INFO, 'GN': GN_INFO, 'GQ': GQ_INFO, 'GR': GR_INFO, 'GT': GT_INFO,
    'GW': GW_INFO, 'GY': GY_INFO, 'HK': HK_INFO, 'HN': HN_INFO, 'HR': HR_INFO,
    'HT': HT_INFO, 'HU': HU_INFO, 'ID': ID_INFO, 'IE': IE_INFO, 'IL': IL_INFO,
    'IM': IM_INFO, 'IN': IN_INFO, 'IQ': IQ_INFO, 'IR': IR_INFO, 'IS': IS_INFO,
    'IT': IT_INFO, 'JE': JE_INFO, 'JM': JM_INFO, 'JO': JO_INFO, 'JP': JP_INFO,
    'KE': KE_INFO, 'KG': KG_INFO, 'KH': KH_INFO, 'KI': KI_INFO, 'KM': KM_INFO,
    'KR': KR_INFO, 'KW': KW_INFO, 'KZ': KZ_INFO, 'LA': LA_INFO, 'LB': LB_INFO, 'LB_OLD': LB_INFO,
    'LC': LC_INFO, 'LI': LI_INFO, 'LK': LK_INFO, 'LR': LR_INFO, 'LS': LS_INFO,
    'LT': LT_INFO, 'LU': LU_INFO, 'LV': LV_INFO, 'LY': LY_INFO, 'MA': MA_INFO,
    'MD': MD_INFO, 'ME': ME_INFO, 'MG': MG_INFO, 'MH': MH_INFO, 'MK': MK_INFO,
    'ML': ML_INFO, 'MM': MM_INFO, 'MN': MN_INFO, 'MO': MO_INFO, 'MR': MR_INFO,
    'MT': MT_INFO, 'MU': MU_INFO, 'MV': MV_INFO, 'MW': MW_INFO, 'MX': MX_INFO,
    'MY': MY_INFO, 'MZ': MZ_INFO, 'NA': NA_INFO, 'NE': NE_INFO, 'NG': NG_INFO,
    'NI': NI_INFO, 'NL': NL_INFO, 'NO': NO_INFO, 'NP': NP_INFO, 'NR': NR_INFO,
    'NU': NU_INFO, 'NZ': NZ_INFO, 'OM': OM_INFO, 'PA': PA_INFO, 'PE': PE_INFO,
    'PG': PG_INFO, 'PH': PH_INFO, 'PK': PK_INFO, 'PL': PL_INFO, 'PS': PS_INFO,
    'PT': PT_INFO, 'PY': PY_INFO, 'QA': QA_INFO, 'RO': RO_INFO, 'RS': RS_INFO,
    'RU': RU_INFO, 'RW': RW_INFO, 'SA': SA_INFO, 'SB': SB_INFO, 'SC': SC_INFO,
    'SD': SD_INFO, 'SE': SE_INFO, 'SG': SG_INFO, 'SI': SI_INFO, 'SK': SK_INFO,
    'SL': SL_INFO, 'SM': SM_INFO, 'SN': SN_INFO, 'SO': SO_INFO, 'SR': SR_INFO,
    'SS': SS_INFO, 'ST': ST_INFO, 'SV': SV_INFO, 'SX': SX_INFO, 'SY': SY_INFO,
    'SZ': SZ_INFO, 'TD': TD_INFO, 'TG': TG_INFO, 'TH': TH_INFO, 'TJ': TJ_INFO,
    'TL': TL_INFO, 'TM': TM_INFO, 'TN': TN_INFO, 'TO': TO_INFO, 'TR': TR_INFO,
    'TT': TT_INFO, 'TV': TV_INFO, 'TW': TW_INFO, 'TZ': TZ_INFO, 'UA': UA_INFO,
    'UG': UG_INFO, 'US': US_INFO, 'UY': UY_INFO, 'UZ': UZ_INFO, 'VA': VA_INFO, 'VC': VC_INFO,
    'VE': VE_INFO, 'VN': VN_INFO, 'VU': VU_INFO, 'WF': WF_INFO, 'WS': WS_INFO, 'XK': XK_INFO,
    'YE': YE_INFO, 'YT': YT_INFO, 'ZA': ZA_INFO, 'ZM': ZM_INFO, 'ZW': ZW_INFO
}, {
    // --- TERRITORIAL FALLBACKS ---
    'AX': 'Aland Islands (follows Finland system)',
    'BV': 'Bouvet Island (follows Norway system)',
    'AS': 'American Samoa (follows USA system)',
    'IO': 'British Indian Ocean Territory (follows UK system)',
    'GU': 'Guam (follows USA system)',
    'FM': 'Micronesia (follows USA system)',
    'PW': 'Palau (follows USA system)',
    'PR': 'Puerto Rico (follows USA system)',
    'SH': 'Saint Helena (follows UK system)',
    'EH': 'Western Sahara (follows Morocco system)',
    'SJ': 'Svalbard and Jan Mayen (follows Norway system)',
    'TK': 'Tokelau (follows New Zealand system)',
    'VA': 'Vatican City (follows Italy system)',
    'NF': 'Norfolk Island (follows Australia system)',
    'CC': 'Cocos (Keeling) Islands (follows Australia system)',
    'CX': 'Christmas Island (follows Australia system)',
    'FK': 'Falkland Islands (follows UK system)',
    'GS': 'South Georgia (follows UK system)',
    'PN': 'Pitcairn (follows UK system)',
    'NC': 'New Caledonia (follows France system)',
    'YT': 'Mayotte (follows France system)',
    'HM': 'Heard and McDonald Islands (follows Australia system)',
    'MP': 'Northern Mariana Islands (follows USA system)',
    'UM': 'US Minor Outlying Islands (follows USA system)',
    'VI': 'US Virgin Islands (follows USA system)',
    'GP': 'Guadeloupe (follows France system)',
    'GF': 'French Guiana (follows France system)',
    'MQ': 'Martinique (follows France system)',
    'PF': 'French Polynesia (follows France system)',
    'RE': 'Reunion (follows France system)',
    'BL': 'Saint Barthelemy (follows France system)',
    'MF': 'Saint Martin (follows France system)',
    'PM': 'Saint Pierre and Miquelon (follows France system)',
    'TF': 'French Southern Territories (follows France system)',
    'WF': 'Wallis and Futuna (follows France system)'
});

export const VALIDATORS = buildRegistry({
    'AD': validateADTIN, 'AE': validateAETIN, 'AF': validateAFTIN, 'AG': validateAGTIN, 'AI': validateAITIN,
    'AL': validateALTIN, 'AM': validateAMTIN, 'AO': validateAOTIN, 'AR': validateARTIN,
    'AT': validateATTIN, 'AU': validateAUTIN, 'AW': validateAWTIN, 'AZ': validateAZTIN,
    'BA': validateBATIN, 'BB': validateBBTIN, 'BD': validateBDTIN, 'BE': validateBETIN,
    'BF': validateBFTIN, 'BG': validateBGTIN, 'BH': validateBHTIN, 'BI': validateBITIN, 'BJ': validateBJTIN,
    'BN': validateBNTIN, 'BO': validateBOTIN, 'BQ': validateBQTIN, 'BR': validateBRTIN,
    'BS': validateBSTIN, 'BT': validateBTTIN, 'BW': validateBWTIN, 'BY': validateBYTIN,
    'BZ': validateBZTIN, 'CA': validateCATIN, 'CD': validateCDTIN, 'CF': validateCFTIN,
    'CG': validateCGTIN, 'CH': validateCHTIN, 'CI': validateCITIN, 'CK': validateCKTIN,
    'CL': validateCLTIN, 'CM': validateCMTIN, 'CN': validateCNTIN, 'CO': validateCOTIN,
    'CR': validateCRTIN, 'CU': validateCUTIN, 'CV': validateCVTIN, 'CW': validateCWTIN,
    'CY': validateCYTIN, 'CZ': validateCZTIN, 'DE': validateDETIN, 'DJ': validateDJTIN,
    'DK': validateDKTIN, 'DM': validateDMTIN, 'DO': validateDOTIN, 'DZ': validateDZTIN,
    'EC': validateECTIN, 'EE': validateEETIN, 'EG': validateEGTIN, 'ER': validateERTIN,
    'ES': validateESTIN, 'ET': validateETTIN, 'FI': validateFITIN, 'FJ': validateFJTIN,
    'FO': validateFOTIN, 'FR': validateFRTIN, 'GA': validateGATIN, 'GB': validateGBTIN,
    'GD': validateGDTIN, 'GE': validateGETIN, 'GG': validateGGTIN, 'GH': validateGHTIN,
    'GI': validateGITIN, 'GL': validateGLTIN, 'GM': validateGMTIN, 'GN': validateGNTIN,
    'GQ': validateGQTIN, 'GR': validateGRTIN, 'GT': validateGTTIN, 'GW': validateGWTIN,
    'GY': validateGYTIN, 'HK': validateHKTIN, 'HN': validateHNTIN, 'HR': validateHRTIN,
    'HT': validateHTTIN, 'HU': validateHUTIN, 'ID': validateIDTIN, 'IE': validateIETIN,
    'IL': validateILTIN, 'IM': validateIMTIN, 'IN': validateINTIN, 'IQ': validateIQTIN,
    'IR': validateIRTIN, 'IS': validateISTIN, 'IT': validateITTIN, 'JE': validateJETIN,
    'JM': validateJMTIN, 'JO': validateJOTIN, 'JP': validateJPTIN, 'KE': validateKETIN,
    'KG': validateKGTIN, 'KH': validateKHTIN, 'KI': validateKITIN, 'KM': validateKMTIN,
    'KR': validateKRTIN_Orig, 'KW': validateKWTIN, 'KZ': validateKZTIN, 'LA': validateLATIN,
    'LB': validateLBTIN, 'LB_OLD': validateLBTIN, 'LC': validateLCTIN, 'LI': validateLITIN, 'LK': validateLKTIN,
    'LR': validateLRTIN, 'LS': validateLSTIN, 'LT': validateLTTIN, 'LU': validateLUTIN,
    'LV': validateLVTIN, 'LY': validateLYTIN, 'MA': validateMATIN, 'MD': validateMDTIN,
    'ME': validateMETIN, 'MG': validateMGTIN, 'MH': validateMHTIN, 'MK': validateMKTIN,
    'ML': validateMLTIN, 'MM': validateMMTIN, 'MN': validateMNTIN, 'MO': validateMOTIN,
    'MR': validateMRTIN, 'MT': validateMTTIN, 'MU': validateMUTIN, 'MV': validateMVTIN,
    'MW': validateMWTIN, 'MX': validateMXTIN, 'MY': validateMYTIN, 'MZ': validateMZTIN,
    'NA': validateNATIN, 'NE': validateNETIN, 'NG': validateNGTIN, 'NI': validateNITIN,
    'NL': validateNLTIN, 'NO': validateNOTIN, 'NP': validateNPTIN, 'NR': validateNRTIN,
    'NU': validateNUTIN, 'NZ': validateNZTIN, 'OM': validateOMTIN, 'PA': validatePATIN,
    'PE': validatePETIN, 'PG': validatePGTIN, 'PH': validatePHTIN, 'PK': validatePKTIN,
    'PL': validatePLTIN, 'PS': validatePSTIN, 'PT': validatePTTIN, 'PY': validatePYTIN,
    'QA': validateQATIN, 'RO': validateROTIN, 'RS': validateRSTIN, 'RU': validateRUTIN,
    'RW': validateRWTIN, 'SA': validateSATIN, 'SB': validateSBTIN, 'SC': validateSCTIN,
    'SD': validateSDTIN, 'SE': validateSETIN, 'SG': validateSGTIN, 'SI': validateSITIN,
    'SK': validateSKTIN, 'SL': validateSLTIN, 'SM': validateSMTIN, 'SN': validateSNTIN,
    'SO': validateSOTIN, 'SR': validateSRTIN, 'SS': validateSSTIN, 'ST': validateSTTIN,
    'SV': validateSVTIN, 'SX': validateSXTIN, 'SY': validateSYTIN, 'SZ': validateSZTIN,
    'TD': validateTDTIN, 'TG': validateTGTIN, 'TH': validateTHTIN, 'TJ': validateTJTIN,
    'TL': validateTLTIN, 'TM': validateTMTIN, 'TN': validateTNTIN, 'TO': validateTOTIN,
    'TR': validateTRTIN, 'TT': validateTTTIN, 'TV': validateTVTIN, 'TW': validateTWTIN,
    'TZ': validateTZTIN, 'UA': validateUATIN, 'UG': validateUGTIN, 'UK': validateGBTIN,
    'US': validateUSTIN, 'UY': validateUYTIN, 'UZ': validateUZTIN, 'VA': validateVATIN, 'VC': validateVCTIN,
    'VE': validateVETIN, 'VN': validateVNTIN, 'VU': validateVUTIN, 'WF': validateWFTIN, 'WS': validateWSTIN,
    'XK': validateXKTIN, 'YE': validateYETIN, 'YT': validateYTTIN, 'ZA': validateZATIN, 'ZM': validateZMTIN,
    'ZW': validateZWTIN
});

// --- RE-EXPORTS ---
export {
    validateADTIN, validateAETIN, validateAFTIN, validateAGTIN, validateAITIN, validateALTIN,
    validateAMTIN, validateAOTIN, validateARTIN, validateATTIN, validateAUTIN,
    validateAWTIN, validateAZTIN, validateBATIN, validateBBTIN, validateBDTIN,
    validateBETIN, validateBFTIN, validateBGTIN, validateBHTIN, validateBITIN, validateBJTIN,
    validateBNTIN, validateBOTIN, validateBQTIN, validateBRTIN, validateBSTIN,
    validateBTTIN, validateBWTIN, validateBYTIN, validateBZTIN, validateCATIN,
    validateCDTIN, validateCFTIN, validateCGTIN, validateCHTIN, validateCITIN,
    validateCKTIN, validateCLTIN, validateCMTIN, validateCNTIN, validateCOTIN,
    validateCRTIN, validateCUTIN, validateCVTIN, validateCWTIN, validateCYTIN,
    validateCZTIN, validateDETIN, validateDJTIN, validateDKTIN, validateDMTIN,
    validateDOTIN, validateDZTIN, validateECTIN, validateEETIN, validateEGTIN,
    validateERTIN, validateESTIN, validateETTIN, validateFITIN, validateFJTIN,
    validateFOTIN, validateFRTIN, validateGATIN, validateGBTIN, validateGDTIN,
    validateGETIN, validateGGTIN, validateGHTIN, validateGITIN, validateGLTIN,
    validateGMTIN, validateGNTIN, validateGQTIN, validateGRTIN, validateGTTIN,
    validateGWTIN, validateGYTIN, validateHKTIN, validateHNTIN, validateHRTIN,
    validateHTTIN, validateHUTIN, validateIDTIN, validateIETIN, validateILTIN,
    validateIMTIN, validateINTIN, validateIQTIN, validateIRTIN, validateISTIN,
    validateITTIN, validateJETIN, validateJMTIN, validateJOTIN, validateJPTIN,
    validateKETIN, validateKGTIN, validateKHTIN, validateKITIN, validateKMTIN,
    validateKRTIN_Orig, validateKWTIN, validateKZTIN, validateLATIN, validateLBTIN,
    validateLCTIN, validateLITIN, validateLKTIN, validateLRTIN, validateLSTIN,
    validateLTTIN, validateLUTIN, validateLVTIN, validateLYTIN, validateMATIN,
    validateMDTIN, validateMETIN, validateMGTIN, validateMHTIN, validateMKTIN,
    validateMLTIN, validateMMTIN, validateMNTIN, validateMOTIN, validateMRTIN,
    validateMTTIN, validateMUTIN, validateMVTIN, validateMWTIN, validateMXTIN,
    validateMYTIN, validateMZTIN, validateNATIN, validateNETIN, validateNGTIN,
    validateNITIN, validateNLTIN, validateNOTIN, validateNPTIN, validateNRTIN,
    validateNUTIN, validateNZTIN, validateOMTIN, validatePATIN, validatePETIN,
    validatePGTIN, validatePHTIN, validatePKTIN, validatePLTIN, validatePSTIN,
    validatePTTIN, validatePYTIN, validateQATIN, validateROTIN, validateRSTIN,
    validateRUTIN, validateRWTIN, validateSATIN, validateSBTIN, validateSCTIN,
    validateSDTIN, validateSETIN, validateSGTIN, validateSITIN, validateSKTIN,
    validateSLTIN, validateSMTIN, validateSNTIN, validateSOTIN, validateSRTIN,
    validateSSTIN, validateSTTIN, validateSVTIN, validateSXTIN, validateSYTIN,
    validateSZTIN, validateTDTIN, validateTGTIN, validateTHTIN, validateTJTIN,
    validateTLTIN, validateTMTIN, validateTNTIN, validateTOTIN, validateTRTIN,
    validateTTTIN, validateTVTIN, validateTWTIN, validateTZTIN, validateUATIN,
    validateUGTIN, validateUSTIN, validateUYTIN, validateUZTIN, validateVATIN, validateVCTIN,
    validateVETIN, validateVNTIN, validateVUTIN, validateWSTIN, validateWFTIN, validateXKTIN,
    validateYETIN, validateYTTIN, validateZATIN, validateZMTIN, validateZWTIN
};
